### ISSUE TITLE
GSYNC/Freesync brightness flickering in games

### ISSUE THREAD

**Issue by kesu1** [Nukem9/dlssg-to-fsr3#308]
Enabling FSR 3 makes the game flicker by randomly dimming/un-dimming. Sometimes it disappears/weakens, but it is definitely there. 

This issue was observed in the following games I tested so far:
- Cyberpunk 2077 (from the loading screen where you need to press the spacebar)
- Witcher 3

I have an RTX 3070 with driver version 546.33
Display: LG 24GN650-B

**Comment by Gaffer13** [comment]
Sounds like regular Freesync brightness flickering. Either FSR results in stuttering or framerate is steady, but in the range that makes the monitor go in and out of frame doubling. So I'd be checking frametimes with Afterburner.

**Comment by kesu1** [comment]
If it is a Freesync Brightness Stutter, why is it present, if my frames are inside the range? What could solve it in this case?

**Comment by Gaffer13** [comment]
It's present because brightness inside the Freesync range may vary on some monitors, and heavy stuttering amounts to framerate going from e.g. 60 fps to 100 and back to 60, from frame to frame. If the monitor looks slightly brighter at 100Hz, compared to 60, you're going to notice rapid changes from 100fps to 60fps. 

The solution is to minimize stuttering, possibly by using a framerate limiter - in this case Nvidia's limiter, though some people report good results from double limiting - a slightly lower limit in the game, a slightly higher limit (that's still below the monitor's maximum refresh rate) in Nvidia Control panel.

**Comment by kesu1** [comment]
Thank you!
Will report back if frame limiting is working or if I checked frame times and found something.

**Comment by kesu1** [comment]
Frametimes seem to fluctuate between 6-12 usually while FPS stays constant. My other monitor with the same VRR range from a different manufacturer does not seem to suffer from this.

**Comment by kesu1** [comment]
This flickerimg is not a problem in my experience if I just lower the settings and achieve the ~same FPS that way.

**Comment by ImASadBoy** [comment]
This sounds like you monitor Freesync problem, not every refrashrate supported has the same gamma sadly, that's why nvidia makes the gsync certification

**Comment by kesu1** [comment]
The problem is with how NVIDIA cards handle FreeSync. LFC will trigger at 60fps even though my monitor's VRR range is 40-144 Hz. Using CRU to make the VRR range narrower helped me eliminate the problem.
Source: https://www.reddit.com/r/nvidia/comments/ap6i5l/one_big_difference_in_nvidias_adaptive_sync/

**Comment by kesu1** [comment]
The problem is with how NVIDIA cards handle FreeSync. LFC will trigger at 60fps even though my monitor's VRR range is 40-144 Hz. Using CRU to make the VRR range narrower helped me eliminate the problem.
Source: https://www.reddit.com/r/nvidia/comments/ap6i5l/one_big_difference_in_nvidias_adaptive_sync/
