### ISSUE TITLE
Cyberpunk 2077 wont lunch

### ISSUE THREAD

**Issue by Gavinbots1** [Nukem9/dlssg-to-fsr3#76]
I did all the steps and followed it correctly I changed the dlss now it won't stop crashing right when the cd logo pops up I tired the 4 and 3 versions none of those versions work should i use the dlss tweak one? please help thanks so much 🙏 
I have a 3080 and Intel 7 12700kf

**Comment by Z4ndyz** [comment]
Might i suggest you

This,  delete your x64 folder from the bin and let cp2077 verify files integrity it will add it back then

I'll let you know what i did for cp2077 with dlsstweaks maybe it'll work for you

Basically get the latest DLSSTweaks and copypaste it's nvngx.dll and dlsstweaks.ini and put them near the .exe of the game
The included EnableNvidiaSigOverride.reg can install this tweak for you (the tweak can also be removed via the DisableNvidiaSigOverride.reg) use it from dlsstweaks rightclick and hit merge

Now get 0.50dlsstweaksedition and add the wrapper dll and fsr3 dll and follow the readme instructions from it

DLSSTweaks may be obtained from: https://github.com/emoose/DLSSTweaks
dlssg-to-fsr3 may be obtained from: https://github.com/Nukem9/dlssg-to-fsr3

================================
===== Install instructions =====
Locate your game's installation directory with DLSSTweaks (e.g. _nvngx.dll) installed.

Copy "dlssg_dlsstweaks_wrapper.dll" and "dlssg_to_fsr3_amd_is_better.dll" to your game's installation directory.

Find "dlsstweaks.ini" and open it in Notepad.

Find the line "[DLLPathOverrides]" after scrolling down to the middle of the INI file.

Find the line ";nvngx_dlssg = C:\Users\Username...\nvngx_dlssg.dll" underneath.

Replace the line with "nvngx_dlssg = C:\Path\To\The\Game\dlssg_dlsstweaks_wrapper.dll".

You MUST TYPE THE FULL DLL PATH and remove the ";" at the beginning. Dlssg-to-fsr3 may not work otherwise.

Done. Launch the game. You'll see a message box on startup.

It has to be specifically dlsstweaks' nvngx.dll(from emoose), dont use the one from 0.50 nondlsstweaks edition

[DLLPathOverrides]
nvngx_dlssg=E:\SteamLibrary\steamapps\common\Cyberpunk 2077\bin\x64\dlssg_dlsstweaks_wrapper.dll for cp2077 looks like this for me

Let me know if it works

from another post try this it should work

**Comment by ForthtuN** [comment]
> I did all the steps and followed it correctly I changed the dlss now it won't stop crashing right when the cd logo pops up I tired the 4 and 3 versions none of those versions work should i use the dlss tweak one? please help thanks so much 🙏 I have a 3080 and Intel 7 12700kf

HDR?

**Comment by Gavinbots1** [comment]
I'm using hdr yeah

**Comment by Gavinbots1** [comment]
you can't just rwd that now I'll try it sorry

**Comment by Gavinbots1** [comment]
well how would I go about disabling it if I can't even get in?

**Comment by ForthtuN** [comment]
Inactivate the mod and disable it then enable mod again

**Comment by Gavinbots1** [comment]
damn that's a bummer cause I really really do like hdr in some of my games

**Comment by Gavinbots1** [comment]
thanks for the help going ti try it now

**Comment by Gavinbots1** [comment]
works amazing now thanks a bunch

**Comment by Gavinbots1** [comment]
Works amazing now and helps so much thanks a ton
